version: '3'

networks:
  probius-dev:

volumes:
  database-data:

services:
  database:
    image: 'postgres:12'
    env_file: .env.development
    networks:
      - probius-dev
    ports:
      - 15432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
  redis:
    image: 'redis:6'
    env_file: .env.development
    networks:
      - probius-dev
    ports:
      - 16379:6379
