package units

type Building struct {
	Name string
}

var Buildings = map[string]Building{
	// Protoss
	"Nexus":            Building{"Nexus"},
	"Pylon":            Building{"Pylon"},
	"Assimilator":      Building{"Assimilator"},
	"Gateway":          Building{"Gateway"},
	"WarpGate":         Building{"Warpgate"},
	"Forge":            Building{"Forge"},
	"PhotonCannon":     Building{"Photon Cannon"},
	"ShieldBattery":    Building{"Shield Battery"},
	"CyberneticsCore":  Building{"Cybernetics Core"},
	"TwilightCouncil":  Building{"Twilight Council"},
	"RoboticsFacility": Building{"Robotics Facility"},
	"Stargate":         Building{"Stargate"},
	"TemplarArchive":   Building{"Templar Archives"},
	"DarkShrine":       Building{"Dark Shrine"},
	"RoboticsBay":      Building{"Robotics Bay"},
	"FleetBeacon":      Building{"Fleet Beacon"},
	// Terran
	"CommandCenter":       Building{"Command Center"},
	"CommandCenterFlying": Building{"Command Center"},
	"OrbitalCommand":      Building{"Orbital Command"},
	"PlanetaryFortress":   Building{"Planetary Fortress"},
	"SupplyDepot":         Building{"Supply Depot"},
	"SupplyDepotLowered":  Building{"Supply Depot"},
	"Refinery":            Building{"Refinery"},
	"Barracks":            Building{"Barracks"},
	"BarracksFlying":      Building{"Barracks"},
	"BarracksReactor":     Building{"Barracks (Reactor)"},
	"BarracksTechLab":     Building{"Barracks (Tech Lab)"},
	"EngineeringBay":      Building{"Engineering Bay"},
	"Bunker":              Building{"Bunker"},
	"MissileTurret":       Building{"Missile Turret"},
	"SensorTower":         Building{"Sensor Tower"},
	"Factory":             Building{"Factory"},
	"FactoryFlying":       Building{"Factory"},
	"FactoryReactor":      Building{"Factory (Reactor)"},
	"FactoryTechLab":      Building{"Factory (Tech Lab)"},
	"GhostAcademy":        Building{"Ghost Academy"},
	"Armory":              Building{"Armory"},
	"Starport":            Building{"Starport"},
	"StarportFlying":      Building{"Starport"},
	"StarportReactor":     Building{"Starport (Reactor)"},
	"StarportTechLab":     Building{"Starport (Tech Lab)"},
	"FusionCore":          Building{"Fusion Core"},
	"TechLab":             Building{"Tech Lab"},
	"Reactor":             Building{"Reactor"},
	// Zerg
	"Hatchery":           Building{"Hatchery"},
	"Extractor":          Building{"Extractor"},
	"SpawningPool":       Building{"Spawning Pool"},
	"EvolutionChamber":   Building{"Evolution Chamber"},
	"SpineCrawler":       Building{"Spine Crawler"},
	"SporeCrawler":       Building{"Spore Crawler"},
	"RoachWarren":        Building{"Roach Warren"},
	"BanelingNest":       Building{"Baneling Nest"},
	"Lair":               Building{"Lair"},
	"HydraliskDen":       Building{"Hydralisk Den"},
	"LurkerDenMP":        Building{"Lurker Den"},
	"InfestationPit":     Building{"Infestation Pit"},
	"Spire":              Building{"Spire"},
	"NydusNetwork":       Building{"Nydus Network"},
	"NydusCanal":         Building{"Nydus Worm"},
	"Hive":               Building{"Hive"},
	"UltraliskCavern":    Building{"Ultralisk Cavern"},
	"GreaterSpire":       Building{"Greater Spire"},
	"CreepTumorBurrowed": Building{"Creep Tumor"},
}
