package units

type Unit struct {
	Name   string
	Supply float64
}

var Units = map[string]Unit{
	// Protoss
	"Probe":            Unit{"Probe", 1},
	"Zealot":           Unit{"Zealot", 2},
	"Sentry":           Unit{"Sentry", 2},
	"Stalker":          Unit{"Stalker", 2},
	"Adept":            Unit{"Adept", 2},
	"HighTemplar":      Unit{"High Templar", 2},
	"DarkTemplar":      Unit{"Dark Templar", 2},
	"Archon":           Unit{"Archon", 4},
	"Observer":         Unit{"Observer", 1},
	"WarpPrism":        Unit{"Warp Prism", 2},
	"WarpPrismPhasing": Unit{"Warp Prism", 2},
	"Immortal":         Unit{"Immortal", 4},
	"Colossus":         Unit{"Colossus", 6},
	"Disruptor":        Unit{"Disruptor", 3},
	"Phoenix":          Unit{"Phoenix", 2},
	"VoidRay":          Unit{"Void Ray", 4},
	"Oracle":           Unit{"Oracle", 3},
	"Tempest":          Unit{"Tempest", 5},
	"Carrier":          Unit{"Carrier", 6},
	"Mothership":       Unit{"Mothership", 8},
	// Terran
	"SCV":               Unit{"SCV", 1},
	"Marine":            Unit{"Marine", 1},
	"Marauder":          Unit{"Marauder", 2},
	"Reaper":            Unit{"Reaper", 1},
	"GhostAlternate":    Unit{"Ghost", 2},
	"Hellion":           Unit{"Hellion", 2},
	"HellionTank":       Unit{"Hellbat", 2},
	"WidowMine":         Unit{"Widow Mine", 2},
	"WidowMineBurrowed": Unit{"Widow Mine", 2},
	"SiegeTank":         Unit{"Siege Tank", 3},
	"SiegeTankSieged":   Unit{"Siege Tank", 3},
	"Cyclone":           Unit{"Cyclone", 3},
	"Thor":              Unit{"Thor", 6},
	"ThorAP":            Unit{"Thor", 6},
	"VikingFighter":     Unit{"Viking", 2},
	"VikingAssault":     Unit{"Viking", 2},
	"Medivac":           Unit{"Medivac", 2},
	"Liberator":         Unit{"Liberator", 3},
	"LiberatorAG":       Unit{"Liberator", 3},
	"Banshee":           Unit{"Banshee", 3},
	"Raven":             Unit{"Raven", 2},
	"Battlecruiser":     Unit{"Battlecruiser", 6},
	// Zerg
	"Drone":             Unit{"Drone", 1},
	"Queen":             Unit{"Queen", 2},
	"Zergling":          Unit{"Zergling", 0.5},
	"Baneling":          Unit{"Baneling", 0.5},
	"Roach":             Unit{"Roach", 2},
	"Ravager":           Unit{"Ravager", 3},
	"Hydralisk":         Unit{"Hydralisk", 2},
	"LurkerMP":          Unit{"Lurker", 3},
	"LurkerMPBurrowed":  Unit{"Lurker", 3},
	"Infestor":          Unit{"Infestor", 2},
	"SwarmHostMP":       Unit{"Swarm Host", 3},
	"Ultralisk":         Unit{"Ultralisk", 6},
	"Overlord":          Unit{"Overlord", 0},
	"OverlordTransport": Unit{"Overlord", 0},
	"Overseer":          Unit{"Overseer", 0},
	"Mutalisk":          Unit{"Mutalisk", 2},
	"Corruptor":         Unit{"Corruptor", 2},
	"Viper":             Unit{"Viper", 3},
	"BroodLord":         Unit{"Brood Lord", 4},
}

type Building struct {
	Name string
}

var Buildings = map[string]Building{
	// Protoss
	"Nexus":            Building{"Nexus"},
	"Pylon":            Building{"Pylon"},
	"Assimilator":      Building{"Assimilator"},
	"Gateway":          Building{"Gateway"},
	"WarpGate":         Building{"Warpgate"},
	"Forge":            Building{"Forge"},
	"PhotonCannon":     Building{"Photon Cannon"},
	"ShieldBattery":    Building{"Shield Battery"},
	"CyberneticsCore":  Building{"Cybernetics Core"},
	"TwilightCouncil":  Building{"Twilight Council"},
	"RoboticsFacility": Building{"Robotics Facility"},
	"Stargate":         Building{"Stargate"},
	"TemplarArchive":   Building{"Templar Archives"},
	"DarkShrine":       Building{"Dark Shrine"},
	"RoboticsBay":      Building{"Robotics Bay"},
	"FleetBeacon":      Building{"Fleet Beacon"},
	// Terran
	"CommandCenter":       Building{"Command Center"},
	"CommandCenterFlying": Building{"Command Center"},
	"OrbitalCommand":      Building{"Orbital Command"},
	"PlanetaryFortress":   Building{"Planetary Fortress"},
	"SupplyDepot":         Building{"Supply Depot"},
	"SupplyDepotLowered":  Building{"Supply Depot"},
	"Refinery":            Building{"Refinery"},
	"Barracks":            Building{"Barracks"},
	"BarracksFlying":      Building{"Barracks"},
	"BarracksReactor":     Building{"Barracks (Reactor)"},
	"BarracksTechLab":     Building{"Barracks (Tech Lab)"},
	"EngineeringBay":      Building{"Engineering Bay"},
	"Bunker":              Building{"Bunker"},
	"MissileTurret":       Building{"Missile Turret"},
	"SensorTower":         Building{"Sensor Tower"},
	"Factory":             Building{"Factory"},
	"FactoryFlying":       Building{"Factory"},
	"FactoryReactor":      Building{"Factory (Reactor)"},
	"FactoryTechLab":      Building{"Factory (Tech Lab)"},
	"GhostAcademy":        Building{"Ghost Academy"},
	"Armory":              Building{"Armory"},
	"Starport":            Building{"Starport"},
	"StarportFlying":      Building{"Starport"},
	"StarportReactor":     Building{"Starport (Reactor)"},
	"StarportTechLab":     Building{"Starport (Tech Lab)"},
	"FusionCore":          Building{"Fusion Core"},
	"TechLab":             Building{"Tech Lab"},
	"Reactor":             Building{"Reactor"},
	// Zerg
	"Hatchery":           Building{"Hatchery"},
	"Extractor":          Building{"Extractor"},
	"SpawningPool":       Building{"Spawning Pool"},
	"EvolutionChamber":   Building{"Evolution Chamber"},
	"SpineCrawler":       Building{"Spine Crawler"},
	"SporeCrawler":       Building{"Spore Crawler"},
	"RoachWarren":        Building{"Roach Warren"},
	"BanelingNest":       Building{"Baneling Nest"},
	"Lair":               Building{"Lair"},
	"HydraliskDen":       Building{"Hydralisk Den"},
	"LurkerDenMP":        Building{"Lurker Den"},
	"InfestationPit":     Building{"Infestation Pit"},
	"Spire":              Building{"Spire"},
	"NydusNetwork":       Building{"Nydus Network"},
	"NydusCanal":         Building{"Nydus Worm"},
	"Hive":               Building{"Hive"},
	"UltraliskCavern":    Building{"Ultralisk Cavern"},
	"GreaterSpire":       Building{"Greater Spire"},
	"CreepTumorBurrowed": Building{"Creep Tumor"},
}

type Upgrade struct {
	Name string
}

var Upgrades = map[string]Upgrade{
	// Protoss
	"ProtossGroundWeaponsLevel1": Upgrade{"Ground Weapons 1"},
	"ProtossGroundWeaponsLevel2": Upgrade{"Ground Weapons 2"},
	"ProtossGroundWeaponsLevel3": Upgrade{"Ground Weapons 3"},
	"ProtossAirWeaponsLevel1":    Upgrade{"Air Weapons 1"},
	"ProtossAirWeaponsLevel2":    Upgrade{"Air Weapons 2"},
	"ProtossAirWeaponsLevel3":    Upgrade{"Air Weapons 3"},
	"ProtossGroundArmorsLevel1":  Upgrade{"Ground Armor 1"},
	"ProtossGroundArmorsLevel2":  Upgrade{"Ground Armor 2"},
	"ProtossGroundArmorsLevel3":  Upgrade{"Ground Armor 3"},
	"ProtossAirArmorsLevel1":     Upgrade{"Air Armor 1"},
	"ProtossAirArmorsLevel2":     Upgrade{"Air Armor 2"},
	"ProtossAirArmorsLevel3":     Upgrade{"Air Armor 3"},
	"ProtossShieldsLevel1":       Upgrade{"Shields 1"},
	"ProtossShieldsLevel2":       Upgrade{"Shields 2"},
	"ProtossShieldsLevel3":       Upgrade{"Shields 3"},
	"TempestGroundAttackUpgrade": Upgrade{"Tectonic Destabilizers"},
	"Charge":                     Upgrade{"Charge"},
	"ObserverGraviticBooster":    Upgrade{"Gravitic Boosters"},
	"GraviticDrive":              Upgrade{"Gravitic Drive"},
	"VoidRaySpeedUpgrade":        Upgrade{"Flux Vanes"},
	"AdeptPiercingAttack":        Upgrade{"Resonating Glaives"},
	"PhoenixRangeUpgrade":        Upgrade{"Anion Pulse-Crystals"},
	"ExtendedThermalLance":       Upgrade{"Extended Thermal Lance"},
	"PsiStormTech":               Upgrade{"Psionic Storm"},
	"BlinkTech":                  Upgrade{"Blink"},
	"DarkTemplarBlinkUpgrade":    Upgrade{"Shadow Stride"},
	"WarpGateResearch":           Upgrade{"Warp Gate"},
	// Terran
	"TerranInfantryWeaponsLevel1":        Upgrade{"Infantry Weapons 1"},
	"TerranInfantryWeaponsLevel2":        Upgrade{"Infantry Weapons 2"},
	"TerranInfantryWeaponsLevel3":        Upgrade{"Infantry Weapons 3"},
	"TerranVehicleWeaponsLevel1":         Upgrade{"Vehicle Weapons 1"},
	"TerranVehicleWeaponsLevel2":         Upgrade{"Vehicle Weapons 2"},
	"TerranVehicleWeaponsLevel3":         Upgrade{"Vehicle Weapons 3"},
	"TerranShipWeaponsLevel1":            Upgrade{"Ship Weapons 1"},
	"TerranShipWeaponsLevel2":            Upgrade{"Ship Weapons 2"},
	"TerranShipWeaponsLevel3":            Upgrade{"Ship Weapons 3"},
	"TerranInfantryArmorsLevel1":         Upgrade{"Infantry Armor 1"},
	"TerranInfantryArmorsLevel2":         Upgrade{"Infantry Armor 2"},
	"TerranInfantryArmorsLevel3":         Upgrade{"Infantry Armor 3"},
	"TerranVehicleAndShipArmorsLevel1":   Upgrade{"Vehicle and Ship Plating 1"},
	"TerranVehicleAndShipArmorsLevel2":   Upgrade{"Vehicle and Ship Plating 2"},
	"TerranVehicleAndShipArmorsLevel3":   Upgrade{"Vehicle and Ship Plating 3"},
	"BansheeSpeed":                       Upgrade{"Hyperflight Rotors"},
	"MedivacIncreaseSpeedBoost":          Upgrade{"Rapid Reignition System"},
	"SmartServos":                        Upgrade{"Smart Servos"},
	"LiberatorAGRangeUpgrade":            Upgrade{"Advanced Ballistics"},
	"EnhancedShockwaves":                 Upgrade{"Enhanced Shockwaves"},
	"HiSecAutoTracking":                  Upgrade{"Hi-Sec Auto Tracking"},
	"CycloneLockOnDamageUpgrade":         Upgrade{"Mag-Field Accelerator"},
	"BansheeCloak":                       Upgrade{"Cloaking Field"},
	"RavenCorvidReactor":                 Upgrade{"Corvid Reactor"},
	"PunisherGrenades":                   Upgrade{"Concussive Shells"},
	"PersonalCloaking":                   Upgrade{"Personal Cloaking"},
	"Stimpack":                           Upgrade{"Stimpack"},
	"BattlecruiserEnableSpecializations": Upgrade{"Weapon Refit"},
	"DrillClaws":                         Upgrade{"Drilling Claws"},
	"ShieldWall":                         Upgrade{"Combat Shield"},
	"HighCapacityBarrels":                Upgrade{"Infernal Pre-Igniter"},
	"TerranBuildingArmor":                Upgrade{"Neosteel Armor"},
	// Zerg
	"ZergMeleeWeaponsLevel1":   Upgrade{"Melee Attacks 1"},
	"ZergMeleeWeaponsLevel2":   Upgrade{"Melee Attacks 2"},
	"ZergMeleeWeaponsLevel3":   Upgrade{"Melee Attacks 3"},
	"ZergMissileWeaponsLevel1": Upgrade{"Missile Attacks 1"},
	"ZergMissileWeaponsLevel2": Upgrade{"Missile Attacks 2"},
	"ZergMissileWeaponsLevel3": Upgrade{"Missile Attacks 3"},
	"ZergFlyerWeaponsLevel1":   Upgrade{"Flyer Attacks 1"},
	"ZergFlyerWeaponsLevel2":   Upgrade{"Flyer Attacks 2"},
	"ZergFlyerWeaponsLevel3":   Upgrade{"Flyer Attacks 3"},
	"ZergGroundArmorsLevel1":   Upgrade{"Ground Carapace 1"},
	"ZergGroundArmorsLevel2":   Upgrade{"Ground Carapace 2"},
	"ZergGroundArmorsLevel3":   Upgrade{"Ground Carapace 3"},
	"ZergFlyerArmorsLevel1":    Upgrade{"Flyer Carapace 1"},
	"ZergFlyerArmorsLevel2":    Upgrade{"Flyer Carapace 2"},
	"ZergFlyerArmorsLevel3":    Upgrade{"Flyer Carapace 3"},
	"ChitinousPlating":         Upgrade{"Chitinous Plating"},
	"DiggingClaws":             Upgrade{"Adaptive Talons"},
	"AnabolicSynthesis":        Upgrade{"Anabolic Synthesis"},
	"CentrificalHooks":         Upgrade{"Centrifugal Hooks"},
	"GlialReconstitution":      Upgrade{"Glial Reconstitution"},
	"zerglingmovementspeed":    Upgrade{"Metabolic Boost"},
	"overlordspeed":            Upgrade{"Pneumatized Carapace"},
	"EvolveMuscularAugments":   Upgrade{"Muscular Augments"},
	"EvolveGroovedSpines":      Upgrade{"Grooved Spines"},
	"LurkerRange":              Upgrade{"Seismic Spines"},
	"Burrow":                   Upgrade{"Burrow"},
	"NeuralParasite":           Upgrade{"NeuralParasite"},
	"InfestorEnergyUpgrade":    Upgrade{"Pathogen Glands"},
	"zerglingattackspeed":      Upgrade{"Adrenal Glands"},
	"TunnelingClaws":           Upgrade{"Tunneling Claws"},
}
